# Generated by Django 5.0.6 on 2024-06-02 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("online_school", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payments",
            name="link",
            field=models.URLField(
                blank=True, null=True, verbose_name="Ссылка на оплату"
            ),
        ),
        migrations.AddField(
            model_name="payments",
            name="session_id",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Сессия"
            ),
        ),
    ]
