# Generated by Django 5.0.6 on 2024-06-02 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("online_school", "0003_payments_link_payments_session_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payments",
            name="amount",
            field=models.PositiveIntegerField(verbose_name="Сумма платежа"),
        ),
        migrations.AlterField(
            model_name="payments",
            name="link",
            field=models.URLField(
                blank=True, max_length=400, null=True, verbose_name="Ссылка на оплату"
            ),
        ),
    ]
